easy_admin:
    site_name: 'Document Manager'
    entities:
        Document:
            class: App\Entity\Document
            controller: App\Controller\DocumentAdminController
            list:
                actions: ['edit', 'download', 'delete']
                fields:
                    - { property: 'thumbnail', type: 'image' }
                    - name
                    - { property: tags, template: 'EasyAdmin/Document/tags.html.twig' }
                    - { property: 'createdAt', format: 'd/m/Y h:i:s' }
                    - { property: 'updatedAt', format: 'd/m/Y h:i:s' }
            form:
                fields:
                    - name
                    - tags
                    - file
                    - description
        Tag:
            class: App\Entity\Tag
            list:
                fields:
                    - id
                    - name
            form:
                fields:
                    - name
