language: php

php:
  - 7.1

env:
  global:
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: 7.1

sudo: false

before_install:
  - if [[ -v $DEPENDENCIES ]]; then composer require --no-update $DEPENDENCIES; fi;
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - php bin/phpunit

notifications:
  email: matthieu.leorat@protonmail.com
